### ISSUE TITLE
pussy is pixeled

### ISSUE THREAD

**Issue by roflinger** [private-dreamnet/dreampower#16]
https://imgur.com/3D3QaUl

Just like that - no error. anything up to date

**Comment by deeppppp** [comment]
New models (checkpoints) need to be trained with high res images to fix this, work in progress

**Comment by roflinger** [comment]
is there a way to help?

**Comment by deeppppp** [comment]
Yes :)
We're putting together a crowd sourced website to gather all the images to train the new checkpoints.
Stay tuned, should be available soon.
