### ISSUE TITLE
Error : input.png file doesn't exist

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreampower#18]
The current archives for v1.0.0 are missing the input.png sample image.
causing running dreampower without any parameters to exit with:

Error : input.png file doesn't exist
Traceback (most recent call last):
  File "D:\DeepNude\DreamNet\DreamPower\dreampower\main.py", line 346, in <module>
  File "D:\DeepNude\DreamNet\DreamPower\dreampower\main.py", line 192, in main
NameError: name 'exit' is not defined
[6836] Failed to execute script main

solution: input.png will be added to the archives and those will be updated in Mega / MediaFire / Github

**Comment by PommeDroid** [comment]
It shouldn't be better to show the help if no argument is provide ? I thinks it would make more sense than running an example.

**Comment by PommeDroid** [comment]
And the exception is bug, we need to replace exit(1) by sys.exit(1).

**Comment by deeppppp** [comment]
Agreed on both, showing help instead of running input.png and replacing exit(1)
We can rename input.png to sample_input.png to make clear it's an example input.
