### ISSUE TITLE
Should we raise the Python version to 3.7?

### ISSUE THREAD

**Issue by wisp101** [private-dreamnet/dreampower#3]
Copying this over from the Dreamtime Issue Tracker. @deeppppp suggested in [this issue](https://github.com/private-dreamnet/dreamtime/issues/31) that we support python 3.7 rather than 3.6, as pytorch makes wheels for that version too. This seems better imo than depending on [any python version > 3.6.2](https://github.com/private-dreamnet/dreamtime/issues/25). However, this would also make it harder to build on some Linux OSes where python 3.7 isn't in the package manager.

**Comment by PommeDroid** [comment]
For information the [generic python setup](https://github.com/private-dreamnet/dreampower/blob/master/scripts/generic/setup.py) script handle the differents version of python

**Comment by wisp101** [comment]
I saw those, but does anybody use them? And why do we have both that and the platform-specific build scripts?

**Comment by PommeDroid** [comment]
I added them and use them on archlinux and windows7. But it was added after the others scripts and I guess we just keep them all the at end.

**Comment by deeppppp** [comment]
This would be a good time to switch to the generic scripts only, and remove the OS specific scripts.
and with that change made, I believe we'd be ok to move to python 3.7.

**Comment by wisp101** [comment]
I like that idea. I don't think a minimum python version is necessary if we go down that route.

**Comment by PommeDroid** [comment]
Yeah, I agree with @wisp101 no need to increase the python version with we go generic python script only.

**Comment by deeppppp** [comment]
Generic scripts solution implemented
