### ISSUE TITLE
Color reproduction of the final output

### ISSUE THREAD

**Issue by fakeki** [private-dreamnet/dreampower#44]
**Describe the bug**
What's with the colors output? The images come out with different hue, the saturation is overdone and so are the white and black values (both clipping). The results is even worse than that, the blacks are actually grey, there is also some colored noise/artifacts/dithering in and around those darker areas (pubic area,shadows, etc). There are couple issues that may cause it but there has to be an compression/low bit depth/color depth one... Also why is the algorithm even affecting the rest of the image? It generates masks so why would it even change the colors of the rest?

How to reproduce: just make any fake using it, happens 100%, more or less severely.

Version: 1.1.0

Also will there be some kind of seamless method of just putting the faked areas over the original image (using those masks it generates) and support for higher resolutions (as it is the app isn't demanding so I could see it handling 1024x1024 resolution easily).

Looking forward to a fix for it.

**Comment by deeppppp** [comment]
The --color-transfer parameter will run an algorithm after nudification trying to correct this.
It's the first attempt to correct this issue and not perfect yet.

Transfers the color distribution from the source to the target image using the mean and standard deviations of the LAB color space.
This implementation is (loosely) based on to the "Color Transfer between Images" paper by Reinhard et al., 2001.

Putting the fake areas over the original images is connected to the color issue, they would not blend in with the model in the original image.
The --overlay OVERLAY parameter allows you to have the algorithm only nudify a section of the original image, it's defined by coordinates.

Higher resolution input images require the models (checkpoints) to be trained on higher resolution images, and that is work in progress.

**Comment by b4nn3d** [comment]
>Higher resolution input images require the models (checkpoints) to be trained on higher resolution 
>images, and that is work in progress.

if you're thinking about training new models.. well go for a 1:2 aspect ratio. I mean 512*1024, 1024*2048. half resolution to be trained ;)

**Comment by DeZepTup** [comment]
> The --overlay OVERLAY parameter allows you to have the algorithm only nudify a section of the original image, it's defined by coordinates.

Got it fixed.
Hi,
Got it fixed. Issue caused by using color correction only on cropped part.
In resize.py, lines 66, 67
        img = DressToCorrect.correct_color(img, 2)
        img_to_overlay = DressToCorrect.correct_color(img_to_overlay, 2.2)

Found 2 and 2.2 to be the less noticeable.
