### ISSUE TITLE
[Windows] Clear GPU cache before/after run

### ISSUE THREAD

**Issue by jochemstoel** [private-dreamnet/dreampower#55]
**Describe the bug**
The second or third time I run this application prebuilt version, I receive an error that CUDA is out of memory.

**To Reproduce**
1. Download and extract binaries for Windows
2. Install the endpoints using dreampower.exe
3. Run dreampower.exe a few times on different images

**Expected behavior**
I expect the cache of my GPU to be cleared after the process is finished and/or before it starts.

**Enviroment**
 - Version: latest
 - OS: Windows 10 x64
-  GPU: NVIDIA GeForce GTX 1050

**Additional context**
```bash
RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 2.00 GiB total capacity; 564.01 MiB already allocated; 17.85 MiB free; 15.99 MiB cached)
```

**Comment by PommeDroid** [comment]
With the new --disable-persistent-gan normally clean all CUDA memory after each GAN. Using this option should avoid this bug.

https://github.com/private-dreamnet/dreampower/blob/d691f02cb5970158cc379f26dea40de3731aa11d/transform/gan/__init__.py#L79-L83 

Before I add this as a global clean up at this end of all executions the same way, if somebody can validate the option actually fix this.( I am not the tight env to reproduce the bug. : linux and no gpu).

**Comment by jochemstoel** [comment]
The bug described only happens occasionally. It only failed to clear GPU cache occasionally, not at all consistently so there is no real way for me to measure if your _--disable-persistent_ works besides using it every time and seeing over a period of time if it stopped failing every now and then.
How do you suggest I test this?

**Comment by PommeDroid** [comment]
Maybe script that run the command again and again times in loop.
