### ISSUE TITLE
Checkpoint update frequency

### ISSUE THREAD

**Issue by jochemstoel** [private-dreamnet/dreampower#63]
> DreamPower is a fork of deepnude_official but with constant improvements from the developers of DreamNet and the world.

How constant exactly are these improvements? Since I forked this repo, the checkpoints remain at version 0.0.1, I assume new improvements will be pushed to 0.0.2 and do not overwrite 0.0.1?

Maybe it is not a bad idea to build in a small checker into the CLI tool that will tell you when its time to update.

**Comment by deeppppp** [comment]
You will be notified of new checkpoints :)
