### ISSUE TITLE
No picture is produced

### ISSUE THREAD

**Issue by denzelkurry** [private-dreamnet/dreampower#65]
Whenever I try using the app, the picture is processing smoothly, but afterward I get hit with this error:
"DreamPower has reported that the photo has been transformed but the file does not exist! This may be due to a problem saving the photo, verify that DreamPower has write permissions and that your Antivirus is not detecting false positives. It is also possible that DreamPower is ending abruptly due to a major problem."

What can I do to fix it? It does have write permissions, antivirus isn't detecting anything...

**Comment by deeppppp** [comment]
Check if there are any characters in the installation path that may trip up the process.
Try to use only [a-z] and [0-9] in the path name.
If for example your username has other characters in it, then try installing the app in the root folder ( C:\  for Windows OS for example ).
