### ISSUE TITLE
Problem downloading checkpoints

### ISSUE THREAD

**Issue by janakptl00** [private-dreamnet/dreampower#70]
When I try to run main.py in virtual environment get error as below. I am not sure what script is suggesting by ' download them using main.py'

(env2) PS F:\dream> python main.py --input Img.jpg -a ALTERED -s 0:1
usage: main.py [-h] [-d] [-i INPUT] [-o OUTPUT] [--cpu | --gpu GPU]
               [--bsize BSIZE] [--asize ASIZE] [--nsize NSIZE] [--vsize VSIZE]
               [--hsize HSIZE] [-n N_RUNS] [--n-cores N_CORES]
               [--auto-resize | --auto-resize-crop | --auto-rescale | --overlay OVERLAY | --ignore-size]
               [--color-transfer] [-s STEPS] [-a ALTERED] [-c CHECKPOINTS]
               [-j JSON_ARGS] [--json-folder-name JSON_FOLDER_NAME] [-v]
               {gpu-info,checkpoints} ...
main.py: error: Checkpoints file not found in directory F:\dream\checkpoints. You can download them using : main.py checkpoints download

**Comment by deeppppp** [comment]
run:
main.py checkpoints download
